/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 * 
 * 
 * Generated by LanguageCLDRGenScript
 *
 * @generated
 * @emails oncall+i18n_fbt_js
 * @noformat
 * @nogrep
 */
'use strict';

var IntlVariations = require("./IntlVariations");

var IntlCLDRNumberType39 = {
  getVariation: function getVariation(n) {
    return IntlVariations.NUMBER_OTHER;
  }
};
module.exports = IntlCLDRNumberType39;